### ISSUE TITLE
[STORY] view all items

### ISSUE THREAD

**Issue by kiaramand** [arraysin-bran/grace_shopper#5]
as a user/guest, I want to view all items in the store so that I can select an item to view

Depends on:
- [x] #11 define product model
- [x] #12 create AllProducts component
- [x] #14 create product store
- [x] #16 write express route to all products view
