### ISSUE TITLE
[STORY] view individual item

### ISSUE THREAD

**Issue by kiaramand** [arraysin-bran/grace_shopper#7]
as a user, I want to view an individual item so that I can add it to my cart

Depends on:
- [x] #11 define product model
- [x] #13 create SingleProduct component
- [x] #14 create product store
- [x] #15 write express route to single product view
